os:
  - linux

services:
  - docker

language: node_js

node_js:
  - "6.11.1"

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - node
    - node_modules
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
    - $HOME/.yarn-cache

env:
  global:
    - NODE_VERSION=6.11.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false

addons:
  sonarcloud:
    organization: "alanktwong-github"
    token:
      secure: "vlBA1Qr0EjJl4mWNEdNYoVHegcnQpHuiXo9FUMd8x35+6JAPuW57h76Go0gOhW6+zTPuwOxujyAwHHLlv83mD6GhiIkVXJ8S75RD09o9C3Poo8KwpAKUXXveaXiAXMTv91W3aue1sR8Dv+ITwoh3lfPCWo2kEGcCq72q4mtJ8kEcbdPOhGe8x0QJ1H4IZCaRlhujsatG1GZ7sdLmI87SH58M5zfpSLJmUYxNyVvXcoZhjKKOSjPZoH5XTyXUV+1Q/KwSLTkYbW2ZaCgjUK92SYChkWKaxJWanGCZtf1+LDDV4bqoRwHwJRfDarCEUewGcHNgmtWKQao617AcrEeS3ezu/lcl4kUtRosvopFNN5APnu4qYYJzCcsoqEh87xDYg68RkbSaYr0LMbj0tTexmYUeXbTvs1saazwRPxV2bbQQ98gY/3/Z4G40Z5CCgp//aToSNh7zi7tMRldT3mIw/wY0z6ZLDoMA1GzSLaUvrdWWDFaZawOUGaCHQnUIMbBaSQ5iVD9fc6hmg+M/yeyR8GCPxs2sSYomE55lt98uuc0hcdTBCzT5HLySlqFRuyrIoeaKonIgQtuUJ6nOJKi3a/XtHeDTg87JoPraBBwXnrpCUaILPD1ItE5dp17f5onIW9WaG3PbsFZ64Ua/2boj4/Hj99QAZ3e0RHVQ83KNFf0="

before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - chmod +x gradlew
  - ./gradlew clean test
  - yarn test
  - ./gradlew sonarqube
  - ./gradlew bootRepackage -Pprod -x test

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
