language: java
jdk: oraclejdk8

addons:
  sonarqube: true
  sonarcloud:
    organization: "alanktwong-github"
    token:
      secure: "AAhKZkWzjBAOtu9CKmDCRFtIH54Qg6YGzMLC0+Aj8fPLPLHJGkPOCxejtlDOY8KiLRl9PHbIwj+IwpfwsRucyIZZyvlrxEZub5E/R1w/1nHhH9ERU3ELzcrjmQAnQkzPXscjNJGdrOcAUzeOZDeL9KhDSF0h7fBdoG9tej1mu8Cu8ywFvIKt48s7AkRrr6CcEEkY1AVbV42QtLjKjgxpirJWAhwbsRBW4rtTnrUoF2NV9OQX1rd8wlwqJ9ICarPJJP5/Q0jRWKFdpI5q9SOOxunfgkhtxy8ZavNQf/lYFZejvAKAjY1swi9nJliaFms6fELEZej9k1PBxWdxU9Hhhc693BEUc8zeFyInEmlMCplvtkcFpjws285p31TiD2OZRG4Akaz6BRkiMlqQ6FTDXYrGxLoIhZKGBBWIPOEPNFQHwctKy6Z1qgRSQ7jmKqEuRMxjlTVrSmWg3WBsENa0oUoxmLzd5EZyIyWvzHnzNjmd3r3r4x3Uzh9IDrHQe6LgBFPZ6NNHtzF7h4u+IO4ZL48m61MRYI5RcdgpDe2p0bphez9yo8ua+I6BinFAcxIaEbiCKL2ephVF1Hg/5CAZknbPj98L3vs2cImPAkNuWZJ5fnyQSSynHPk55gnWujk2/oxoPYhjZRu/UqWGY+xCmIj/tBPp9aaRXrlPzamwQzc="
 
script:
- ./gradlew clean build